### PR TITLE
Bryan/social-logins

### PR DESCRIPTION
**Pull request by blbergo**
**What is the new behavior that this PR brings (describe or link to an issue)?**
- repo rework
- trad auth flow
- google auth flow
- x auth flow

**PR checklist (requester)**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Your code is documented

### CODE REVIEW

**Review by mgkram4 — COMMENTED** [review]
lgtm! The next code review we have whenever that may be, could you go over 0auth a little? thank you

**Review by yzerr0 — APPROVED** [review]
all looks good!

**Review by thatfoogabriel — APPROVED** [review]
Looks great!

**Review by mgkram4 — COMMENTED** [review]
lgtm!

**Pull request merged**
